export const mockMusic = [
    {
      id: "m1",
      title: "Dil Chahta Hai",
      artist: "Shankar-Ehsaan-Loy",
      genre: "Bollywood",
      image: "/placeholder.svg?height=400&width=400&text=Dil+Chahta+Hai",
      price: "0.05",
      language: "Hindi",
    },
    {
      id: "m2",
      title: "Pasoori",
      artist: "Ali Sethi, Shae Gill",
      genre: "Pop",
      image: "/placeholder.svg?height=400&width=400&text=Pasoori",
      price: "0.04",
      language: "Punjabi",
    },
    {
      id: "m3",
      title: "Chaiyya Chaiyya",
      artist: "Sukhwinder Singh",
      genre: "Bollywood",
      image: "/placeholder.svg?height=400&width=400&text=Chaiyya+Chaiyya",
      price: "0.06",
      language: "Hindi",
    },
    {
      id: "m4",
      title: "Amplifier",
      artist: "Imran Khan",
      genre: "Bhangra",
      image: "/placeholder.svg?height=400&width=400&text=Amplifier",
      price: "0.03",
      language: "Punjabi",
    },
    {
      id: "m5",
      title: "Kal Ho Naa Ho",
      artist: "Sonu Nigam",
      genre: "Bollywood",
      image: "/placeholder.svg?height=400&width=400&text=Kal+Ho+Naa+Ho",
      price: "0.05",
      language: "Hindi",
    },
    {
      id: "m6",
      title: "Mundian To Bach Ke",
      artist: "Panjabi MC",
      genre: "Bhangra",
      image: "/placeholder.svg?height=400&width=400&text=Mundian+To+Bach+Ke",
      price: "0.04",
      language: "Punjabi",
    },
    {
      id: "m7",
      title: "Zindagi Kuch Toh Bata",
      artist: "Jubin Nautiyal",
      genre: "Bollywood",
      image: "/placeholder.svg?height=400&width=400&text=Zindagi+Kuch+Toh+Bata",
      price: "0.05",
      language: "Hindi",
    },
    {
      id: "m8",
      title: "Lahore",
      artist: "Guru Randhawa",
      genre: "Punjabi Pop",
      image: "/placeholder.svg?height=400&width=400&text=Lahore",
      price: "0.04",
      language: "Punjabi",
    },
  ]
  
  